sudo: false
env:
  global:
    secure: "HCfYqxqG0nLPfEZFvyRIv5I+0pbT0MpOEwnZgVDCmRgpLNMhpQ91IISVJjQSOkZVPzGAxPyp7B2oXxEwegpqv6SN4ib41KczkAf6hrAZB/Mu1JPai6XqcfkpJsnqAM1OERnKkBjn+aRHMaYvcTxuIRy6rqD51+MQxOwfalkE3yo8VLngKrrW/nAfJxtq7UAZQNmf3tzSMdk0CgqfqPNW8FTp3JIAuyVSDOmqkPDj80DrKhBdVoNsE0689uagrDkpmw6Uyjd9ATStUVJ4T+uiuMPMoAsaE03pAHSW4vFGvBzEipHovbzo48Xa2qxYzATNNRIJyMua4OeXFqxDZAitoPIHS3nlFmF30zo7WxiqgysPt6P6u8ZPFwz7Ojn0iLOznIQ8XePAhqqD12nuIqLvyz3D3HbBLTqTyj6W2zf6UE5EFoXJ9O00Vk2Oj9XWG8yiOrfGKoXnYIu009LOLanSDz2i5b8KQMpXJlEJrt/l6C60JxLL/rnjs7SRq1JqhsfNcl6Npn7y3lvjBtlngi2eEbA39N5WYB94sUM0NkVqOtht14fTfs9IUTEW2S7qwb6iH+NEtzHMbMuVtMnJAI+jrpFPfJiiSLtz9K8lwFbH5vrZC//PNMSgNfqvxHLxmbe9Ms2F6tIgZqjsd0By+uSR/aI6iseLVCl+F/F6yGY0ulU="  # DEPLOY_REMOTE
script:
  - .travis/deploy
